### ISSUE TITLE
Can you also add what was the exact problem statement, what were the things to be achieved from this project

### ISSUE THREAD

**Issue by RehmanaliMomin** [HarsheetKakar/Streamer#1]

**Comment by HarsheetKakar** [comment]
Hi @RehmanaliMomin as written in the README it is a webapp to stream videos, I just had a day to wrap it up thats why currently it is just setup to stream dummy videos, feel free contribute and add admin user to add more videos.

**Comment by RehmanaliMomin** [comment]
Oh, Okay.
